### ISSUE TITLE
tests installed along with package when doing pip install 

### ISSUE THREAD

**Issue by browniebroke** [founders4schools/duedilv3#6]
The tests are being installed along with the package when installed using pip

**Comment by cleder** [comment]
I think they should be on pypi so any user can test the egg without having to checkout the source

**Comment by browniebroke** [comment]
Yes, but that's different. I'm just talking about not having the test code part of the package I want to use as final user. I think it's wrong to have it available once the package is installed with pip.  I think it's just a matter of putting the tests in a separate folder, the exclude directive in setup.py is already there, and tests have been isolated in the other fork already https://github.com/growthstreet/duedilv3/commit/e33f6906f0d43abe82e907570b8a487299acbf33

**Comment by cleder** [comment]
:+1:
